apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-container
        image: gcr.io/lugx-gaming-465010/order-service:latest
        ports:
        - containerPort: 5001
        env:
          - name: SUPABASE_URL
            valueFrom:
              secretKeyRef:
                name: supabase-secret
                key: SUPABASE_URL
          - name: SUPABASE_KEY
            valueFrom:
              secretKeyRef:
                name: supabase-secret
                key: SUPABASE_KEY

---
apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  type: LoadBalancer
  selector:
    app: order-service
  ports:
    - port: 5001
      targetPort: 5001
