apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analytics-service
  template:
    metadata:
      labels:
        app: analytics-service
    spec:
      containers:
      - name: analytics-container
        image: gcr.io/lugx-gaming-465010/analytics-service:latest
        ports:
        - containerPort: 5002
        resources:
          requests:
            cpu: 250m
            memory: 512Mi
          limits:
            cpu: 500m
            memory: 1Gi
        envFrom:
        - secretRef:
            name: clickhouse-secret
---
apiVersion: v1
kind: Service
metadata:
  name: analytics-service
spec:
  type: LoadBalancer
  selector:
    app: analytics-service
  ports:
  - port: 5002
    targetPort: 5002
