name: CI/CD for Lugx Gaming

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: read
  id-token: write

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - id: 'auth'
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: lugx-gaming-465010
          install_components: gke-gcloud-auth-plugin

      - name: Configure Docker auth
        run: gcloud auth configure-docker gcr.io

      - name: Build & Push Frontend
        run: |
          docker build -t gcr.io/lugx-gaming-465010/lugx-frontend:latest ./
          docker push gcr.io/lugx-gaming-465010/lugx-frontend:latest

      - name: Build & Push Game Service
        run: |
          docker build -t gcr.io/lugx-gaming-465010/game-service:latest ./lugx-microservices/game-service
          docker push gcr.io/lugx-gaming-465010/game-service:latest

      - name: Build & Push Order Service
        run: |
          docker build -t gcr.io/lugx-gaming-465010/order-service:latest ./lugx-microservices/order-service
          docker push gcr.io/lugx-gaming-465010/order-service:latest

      - name: Build & Push Analytics Service
        run: |
          docker build -t gcr.io/lugx-gaming-465010/analytics-service:latest ./lugx-microservices/analytics-service
          docker push gcr.io/lugx-gaming-465010/analytics-service:latest

      - name: Get GKE credentials
        run: gcloud container clusters get-credentials lugx-cluster --region asia-south1

      - name: Deploy frontend
        run: |
          kubectl apply -f k8s-frontend.yaml
          kubectl rollout restart deployment lugx-frontend

      - name: Deploy game service
        run: |
          kubectl apply -f lugx-microservices/game-service/k8s-game-service.yaml
          kubectl rollout restart deployment game-service

      - name: Deploy order service
        run: |
          kubectl apply -f lugx-microservices/order-service/k8s-order-service.yaml
          kubectl rollout restart deployment order-service

      - name: Deploy analytics service
        run: |
          kubectl apply -f lugx-microservices/analytics-service/k8s-analytics-service.yaml
          kubectl rollout restart deployment analytics-service

      - name: Apply ServiceMonitors
        run: |
          kubectl apply -f lugx-microservices/game-service/game-service-monitor.yaml
          kubectl apply -f lugx-microservices/order-service/order-service-monitor.yaml
          kubectl apply -f lugx-microservices/analytics-service/analytics-service-monitor.yaml

      - run: sleep 60

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - run: pip install requests
      - run: python tests/integration_tests.py
